UPDATE receipts
SET PROCESSED_DATE = CASE
   WHEN PROCESSED_DATE LIKE '%.%' THEN STR_TO_DATE(PROCESSED_DATE, '%Y-%m-%dT%H:%i:%s.%fZ')
   ELSE STR_TO_DATE(PROCESSED_DATE, '%Y-%m-%dT%H:%i:%sZ')
END;
ALTER TABLE receipts MODIFY COLUMN PROCESSED_DATE DATETIME(3);